### ISSUE TITLE
Better benchmarks?

### ISSUE THREAD

**Issue by alexandrnikitin** [Scooletz/RampUp#17]
There is just one: https://github.com/Scooletz/RampUp/blob/dc057e466bb5fd5ec995333887ced43945a77128/src/RampUp.Tests/PerformanceTests.cs

It has the following piece of code:
```csharp
var consumer = Task.Factory.StartNew(() =>
{
    var c = 0;
    wait.Wait(t);
    while (c < totalMessageCount)
    {
        buffer.Read((msgdI, chunk) => { c++; }, 10000);
    }
}, t, TaskCreationOptions.LongRunning, scheduler);
```
If you remove the closure of `c` variable you will get ~2x times boost and propably up to 20M messages :wink: 

I believe we need better bechmarks :smile: 
Take a look at https://github.com/PerfDotNet/BenchmarkDotNet

**Comment by Scooletz** [comment]
Yes, the closure + an object without padding, this for sure affects it:) Could you issue a PR for that? I'd be happy to accept it.

For sake of reference:
- Benchmarks have been mentioned at #2 
- Padding has been mentioned at #7

**Comment by Scooletz** [comment]
According to my measurements, closure removal in this case wasn't the best thing I can optimize for. I've done several runs and now the core of the `RampUp` allocates nothing at all. This test have been update as well, but as I mentioned before, the biggest gain was removing of the remaining allocations in the core itself (they were related to `delegates`).

**Comment by alexandrnikitin** [comment]
@Scooletz :+1:  I'll try to make a PR tomorrow with benchmarks.
