### ISSUE TITLE
Consider using Memory/GC benchmarking

### ISSUE THREAD

**Issue by Scooletz** [Scooletz/RampUp#2]
Consider following to apply some memory/GC benchmarking:
- [Benchmark Dot Net](https://github.com/PerfDotNet/BenchmarkDotNet) - investigate this [blog post](http://mattwarren.github.io/2016/02/17/adventures-in-benchmarking-memory-allocations/) if this library can be used for this purpose
- [DotMemory Unit](https://www.jetbrains.com/dotmemory/unit/) - after initial tests it's quite hard to filter out a set of objects as the query is passed to a proxy project, so one cannot adjust test to measure only allocations connected with a test. Additionally, it looks that the measurements performs some allocations on its own, lowering the possibility of getting a measured region without allocations at all.

**Comment by Scooletz** [comment]
Closed by #21

**Comment by mattwarren** [comment]
It's cool to see that you are using BenchmarkDotNet, I've added you to [our list](https://github.com/PerfDotNet/BenchmarkDotNet/wiki/People-using-BenchmarkDotNet)!
